# Generated by Django 5.0.3 on 2024-03-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bakso",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=20)),
                ("gambar", models.FileField(upload_to="bakso/")),
                ("harga", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "kategori",
                    models.CharField(
                        choices=[("bakso", "Bakso"), ("ayam", "Ayam")], max_length=5
                    ),
                ),
            ],
        ),
    ]
