# Generated by Django 5.0.3 on 2024-03-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bakso", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bakso",
            name="deskripsi",
            field=models.TextField(default=None, max_length=256),
        ),
    ]
